# Project: Socket
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o C:/Users/Pathompat/Downloads/hashlib2plus/trunk/src/hl_md5wrapper.o hashlib2plus/trunk/src/hl_md5.o
LINKOBJ  = main.o C:/Users/Pathompat/Downloads/hashlib2plus/trunk/src/hl_md5wrapper.o hashlib2plus/trunk/src/hl_md5.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc "C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libws2_32.a" "C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include/hashlibpp.h"
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Socket.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

C:/Users/Pathompat/Downloads/hashlib2plus/trunk/src/hl_md5wrapper.o: C:/Users/Pathompat/Downloads/hashlib2plus/trunk/src/hl_md5wrapper.cpp
	$(CPP) -c C:/Users/Pathompat/Downloads/hashlib2plus/trunk/src/hl_md5wrapper.cpp -o C:/Users/Pathompat/Downloads/hashlib2plus/trunk/src/hl_md5wrapper.o $(CXXFLAGS)

hashlib2plus/trunk/src/hl_md5.o: hashlib2plus/trunk/src/hl_md5.cpp
	$(CPP) -c hashlib2plus/trunk/src/hl_md5.cpp -o hashlib2plus/trunk/src/hl_md5.o $(CXXFLAGS)
